### ISSUE TITLE
Could the README mention whether this works for the BG2 enhanced edition? And whether there may be any conflicts?

### ISSUE THREAD

**Issue by rubyFeedback** [Pocket-Plane-Group/UnfinishedBusiness#23]
I originally saw it mentioned on a website, but this is a few years old so I was not sure whether it still worked. It said "beta release" so I am not sure.

**Comment by AngelGryph** [comment]
UB has been partially compatible with BG2:EE since version 23 (all but the ranger kits) and compatibility with the ranger kits has been added since version 28.  This is noted in the readme.  No incompatibilities are currently reported.  I will add a note about EE compatibility to the readme (as well as change the reference to the old Baldurdash Fixpack to G3 Fixpack).
