### ISSUE TITLE
Extra items in Minsc inventory after Kidnapping of Boo quest.

### ISSUE THREAD

**Issue by matthew2718** [Pocket-Plane-Group/UnfinishedBusiness#24]
After retrieving Boo from Eleanya, Minsc now has 3 unmovable items in his inventory (Boo Scraps, and 2 identical Boos).
I also installed the option to move Boo from quick slots to his inventory from the "Tweaks Anthology" mod which might have something to do with the issue.

Is the correct behavior to only have a single boo in Minsc's inventory at the end of the quest?
Will it cause any issues with future quests/interactions to remove the extra items from Minsc's inventory via EEKeeper?

**Comment by AngelGryph** [comment]
Yes, the Tweaks Anthology modification causes issues with this quest because the scripts involved assume that Boo is in qitem1.  Since the recommended install order is to install Tweaks after UB, this is something that needs to be fixed in Tweaks.  I can't do anything about it from within UB.

As for your question, no there is no harm in removing the extra items.  They are cosmetic only and don't do anything at all, and there is at the moment no further follow-up to this quest, nor do I intend to create one.
